# Generated by Django 2.0.7 on 2018-08-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180827_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_id',
        ),
    ]
